In [25]:
import pandas as pd
from sqlalchemy import create_engine
import psycopg2

### Store CSV into DataFrame

In [26]:
csv_file = "../Resources/billboard.csv"
billboard_data_df = pd.read_csv(csv_file)
billboard_data_df.head()

,Unnamed: 0,Artists,Name,Weekly.rank,Peak.position,Weeks.on.chart,Week,Date,Genre,Writing.Credits,Lyrics,Features
0,1,"Lil Nas,",Old Town Road,1,1.0,7.0,2019-07-06,"April 5, 2019","Country,Atlanta,Alternative Country,Hip-Hop,Tr...","Jozzy, Atticus ross, Trent reznor, Billy ray c...","Old Town Road Remix \nOh, oh-oh\nOh\nYeah, I'm...",Billy Ray Cyrus
1,2,"Shawn Mendes, Camila Cabello",Senorita,2,NaN,NaN,2019-07-06,"June 21, 2019",Pop,"Cashmere cat, Jack patterson, Charli xcx, Benn...",Senorita \nI love it when you call me senorita...,NaN
2,3,Billie Eilish,Bad Guy,3,2.0,13.0,2019-07-06,"March 29, 2019","Hip-Hop,Dark Pop,House,Trap,Memes,Alternative ...","Billie eilish, Finneas","bad guy \nWhite shirt now red, my bloody nose\...",NaN
3,4,Khalid,Talk,4,3.0,20.0,2019-07-06,"February 7, 2019","Synth-Pop,Pop","Howard lawrence, Guy lawrence, Khalid",Talk \nCan we just talk? Can we just talk?\nTa...,NaN
4,5,"Ed Sheeran, Justin Bieber",I Don't Care,5,2.0,7.0,2019-07-06,"May 10, 2019","Canada,UK,Dance,Dance-Pop,Pop","Ed sheeran, Justin bieber, Shellback, Max mart...",I Don't Care \nI'm at a party I don't wanna be...,NaN

### Create new data with select columns

In [44]:
new_billboard_data_df = billboard_data_df[['Artists', 'Name', 'Weekly.rank', 'Weeks.on.chart', 'Date', 'Genre']].copy()
new_billboard_data_df.head()

,Artists,Name,Weekly.rank,Weeks.on.chart,Date,Genre
0,"Lil Nas,",Old Town Road,1,7.0,"April 5, 2019","Country,Atlanta,Alternative Country,Hip-Hop,Tr..."
1,"Shawn Mendes, Camila Cabello",Senorita,2,NaN,"June 21, 2019",Pop
2,Billie Eilish,Bad Guy,3,13.0,"March 29, 2019","Hip-Hop,Dark Pop,House,Trap,Memes,Alternative ..."
3,Khalid,Talk,4,20.0,"February 7, 2019","Synth-Pop,Pop"
4,"Ed Sheeran, Justin Bieber",I Don't Care,5,7.0,"May 10, 2019","Canada,UK,Dance,Dance-Pop,Pop"

### Clean DataFrame

In [45]:
new_billboard_data_df["New_Genre"] = new_billboard_data_df["Genre"].str.split(",",expand=True)[0]
new_billboard_data_df["New_Artist"] = new_billboard_data_df["Artists"].str.split(",",expand=True)[0]
new_billboard_data_df.head()

,Artists,Name,Weekly.rank,Weeks.on.chart,Date,Genre,New_Genre,New_Artist
0,"Lil Nas,",Old Town Road,1,7.0,"April 5, 2019","Country,Atlanta,Alternative Country,Hip-Hop,Tr...",Country,Lil Nas
1,"Shawn Mendes, Camila Cabello",Senorita,2,NaN,"June 21, 2019",Pop,Pop,Shawn Mendes
2,Billie Eilish,Bad Guy,3,13.0,"March 29, 2019","Hip-Hop,Dark Pop,House,Trap,Memes,Alternative ...",Hip-Hop,Billie Eilish
3,Khalid,Talk,4,20.0,"February 7, 2019","Synth-Pop,Pop",Synth-Pop,Khalid
4,"Ed Sheeran, Justin Bieber",I Don't Care,5,7.0,"May 10, 2019","Canada,UK,Dance,Dance-Pop,Pop",Canada,Ed Sheeran

In [46]:
new_billboard_data_df = new_billboard_data_df.drop(columns=["Artists", "Genre"])
new_billboard_data_df.head()

,Name,Weekly.rank,Weeks.on.chart,Date,New_Genre,New_Artist
0,Old Town Road,1,7.0,"April 5, 2019",Country,Lil Nas
1,Senorita,2,NaN,"June 21, 2019",Pop,Shawn Mendes
2,Bad Guy,3,13.0,"March 29, 2019",Hip-Hop,Billie Eilish
3,Talk,4,20.0,"February 7, 2019",Synth-Pop,Khalid
4,I Don't Care,5,7.0,"May 10, 2019",Canada,Ed Sheeran

In [47]:
new_billboard_data_df.to_csv('/Users/lukefedeli/Desktop/Class_Files/cwru-cle-data-pt-10-2020-u-c/13-ETL-Project/1/Activities/01-Ins_ETL_Pandas/Resources/Cleaned_Billboard.csv', index = False)