In [1]:
import pandas as pd
from sqlalchemy import create_engine
from config import password

In [5]:
# Study data files
billboard_data = "Cleaned_Billboard.csv"
spotify_data = "data/adj_spotify_data.csv"
lyrics_data = "lyrics_final.csv"

# Read the mouse data and the study results
billboard_data = pd.read_csv(billboard_data)
spotify_data = pd.read_csv(spotify_data)
lyrics_data = pd.read_csv(lyrics_data)

lyrics_data.head()

spotify_data.rename(columns = {'name':'Name'}, inplace=True)
#spotify_data.head()

In [6]:
lyrics_data.head()

,Unnamed: 0,Name,cleaned_lyrics,Genre
0,9279,Dark Queen,Dark Queen Dear momma Love momma that's gang A...,"Emo Rap,Alternative,Alternative R&;B,R&;B,Clou..."
1,34055,Beez In The Trap,"Beez In The Trap Yo Man, man Uh Bitches ain't ...","Trap,Rap"
2,42754,Love The Way You Lie,Love Way You Lie Just gonna stand watch burn? ...,"Ballad,Pop,Rap"
3,22672,Shake It Off,Shake It Off stay late Got nothing brain That'...,"Dance-Pop,Pop"
4,96494,We Can't Be Friends,We Can't Be Friends RL To act like never To co...,Pop

In [7]:
billboard_data.drop_duplicates('Name', inplace=True)

In [9]:
merged_data_df = pd.merge(billboard_data, spotify_data, how='right', on='Name')

In [11]:
new_merged_data_df = pd.merge(merged_data_df, lyrics_data, how='right', on='Name')
new_merged_data_df.head(20)

,Name,Weekly.rank,Weeks.on.chart,Date,New_Genre,New_Artist,artists,danceability,energy,popularity,year,Unnamed: 0,cleaned_lyrics,Genre
0,I Like It,45.0,51.0,"April 6, 2018",Trap,Cardi B,"['Cardi B', 'Bad Bunny', 'J Balvin']",0.816,0.726,81.0,2018.0,93378,"Like It Yeah Girl, wish could spend time every...",Pop
1,I Like It,45.0,51.0,"April 6, 2018",Trap,Cardi B,"['Enrique Iglesias', 'Pitbull']",0.646,0.940,63.0,2010.0,93378,"Like It Yeah Girl, wish could spend time every...",Pop
2,I Like It,45.0,51.0,"April 6, 2018",Trap,Cardi B,"['Sammie', 'JT Money']",0.826,0.656,58.0,2000.0,93378,"Like It Yeah Girl, wish could spend time every...",Pop
3,Leave Me Alone,45.0,25.0,"March 14, 2018",Rap,Flipp Dinero,['Flipp Dinero'],0.792,0.743,72.0,2019.0,4017,"Leave Me Alone Yeah, yeah Yeah, miss got time ...",Rap
4,Leave Me Alone,45.0,25.0,"March 14, 2018",Rap,Flipp Dinero,['NF'],0.722,0.741,70.0,2019.0,4017,"Leave Me Alone Yeah, yeah Yeah, miss got time ...",Rap
5,Leave Me Alone,45.0,25.0,"March 14, 2018",Rap,Flipp Dinero,['Flipp Dinero'],0.792,0.743,69.0,2018.0,4017,"Leave Me Alone Yeah, yeah Yeah, miss got time ...",Rap
6,Perfect,21.0,57.0,"March 3, 2017",Adult Contemporary,Ed Sheeran,['Yung Pinch'],0.680,0.542,66.0,2019.0,74139,Perfect If don't take Paris On lover's getaway...,Country
7,Perfect,21.0,57.0,"March 3, 2017",Adult Contemporary,Ed Sheeran,['Ed Sheeran'],0.599,0.448,86.0,2017.0,74139,Perfect If don't take Paris On lover's getaway...,Country
8,Perfect,21.0,57.0,"March 3, 2017",Adult Contemporary,Ed Sheeran,['One Direction'],0.647,0.823,76.0,2015.0,74139,Perfect If don't take Paris On lover's getaway...,Country
9,Perfect,21.0,57.0,"March 3, 2017",Adult Contemporary,Ed Sheeran,['Hollywood Session Group'],0.487,0.520,0.0,2010.0,74139,Perfect If don't take Paris On lover's getaway...,Country
10,Yours,72.0,20.0,"October 24, 2016",Country,Russell Dickerson,['Russell Dickerson'],0.554,0.722,69.0,2017.0,7380,Yours Yours boat stuck bottle That never got c...,Country
11,Dark Queen,91.0,2.0,"August 25, 2017",Emo Rap,Lil Uzi Vert,['Lil Uzi Vert'],0.747,0.606,68.0,2017.0,9279,Dark Queen Dear momma Love momma that's gang A...,"Emo Rap,Alternative,Alternative R&;B,R&;B,Clou..."
12,Swang,50.0,26.0,"August 12, 2016",Memes,Rae Sremmurd,['Rae Sremmurd'],0.681,0.314,72.0,2016.0,11187,"Swang Mmm boy, it's nasty uh Uhmm Know young n...","Memes,Hip-Hop,Trap,Rap"
13,Say It,98.0,4.0,"April 22, 2016",Australia,Flume,['Tory Lanez'],0.546,0.529,70.0,2016.0,17798,Say It Just keeping honest You wouldn't want y...,"Alternative R&;B,Trap,Rap,Canada,R&;B"
14,Say It,98.0,4.0,"April 22, 2016",Australia,Flume,['Ne-Yo'],0.407,0.378,45.0,2007.0,17798,Say It Just keeping honest You wouldn't want y...,"Alternative R&;B,Trap,Rap,Canada,R&;B"
15,Exchange,46.0,34.0,"September 21, 2015",Boom Bap,Bryson Tiller,['Bryson Tiller'],0.525,0.433,78.0,2015.0,15670,"Exchange This happen think bout get feelings, ...","Boom Bap,Singer-Songwriter,Dark Pop,Soul Pop,H..."
16,With You,93.0,7.0,"April 29, 2016",Canada,Drake,"['Kaskade', 'Meghan Trainor']",0.362,0.921,66.0,2019.0,54417,"With You need you, boo gotta see you, boo And ...","DMV,Pop,R&;B"
17,With You,93.0,7.0,"April 29, 2016",Canada,Drake,['Keziah Powell'],0.700,0.539,0.0,2018.0,54417,"With You need you, boo gotta see you, boo And ...","DMV,Pop,R&;B"
18,With You,93.0,7.0,"April 29, 2016",Canada,Drake,"['Drake', 'PARTYNEXTDOOR']",0.878,0.406,61.0,2016.0,54417,"With You need you, boo gotta see you, boo And ...","DMV,Pop,R&;B"
19,With You,93.0,7.0,"April 29, 2016",Canada,Drake,['Chris Brown'],0.662,0.693,71.0,2007.0,54417,"With You need you, boo gotta see you, boo And ...","DMV,Pop,R&;B"

In [15]:
new_merged_data_df.drop(columns=['Weekly.rank'], inplace=True)
new_merged_data_df.drop(columns=['Weeks.on.chart'], inplace=True)
new_merged_data_df.drop(columns=['Unnamed: 0'], inplace=True)
new_merged_data_df.drop(columns=['Genre'], inplace=True)

KeyError: "['Weekly.rank'] not found in axis"

In [16]:
new_merged_data_df.drop(columns=['New_Artist'], inplace=True)
new_merged_data_df.sort_values(by=['year'], ascending=False)

,Name,Date,New_Genre,artists,danceability,energy,popularity,year,cleaned_lyrics
39,A Thousand Years,"November 9, 2012",Screen,['Piano Project'],0.524,0.244,11.0,2019.0,A Thousand Years Heart beats fast Colors promi...
16,With You,"April 29, 2016",Canada,"['Kaskade', 'Meghan Trainor']",0.362,0.921,66.0,2019.0,"With You need you, boo gotta see you, boo And ..."
75,Like You,"January 1, 2005",Rap,"['Marsh', 'Wassu']",0.772,0.849,11.0,2019.0,Like You Yo! Oh It's boy! Oh Daddy Yankee! All...
3,Leave Me Alone,"March 14, 2018",Rap,['Flipp Dinero'],0.792,0.743,72.0,2019.0,"Leave Me Alone Yeah, yeah Yeah, miss got time ..."
4,Leave Me Alone,"March 14, 2018",Rap,['NF'],0.722,0.741,70.0,2019.0,"Leave Me Alone Yeah, yeah Yeah, miss got time ..."
...,...,...,...,...,...,...,...,...,...
90,Rolling In The Deep,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Rolling Deep There's fire starting heart Reach...
91,Last Chance,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Last Chance Ooh yeah, ooh yeah Ooh yeah, liste..."
92,Raining On Sunday,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Raining On Sunday It ticks like Timex It never...
93,She's Like The Wind,NaN,NaN,NaN,NaN,NaN,NaN,NaN,She's Like The Wind Listen baby I've around kn...
94,Sexy Chick,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Sexy Chick Yes, see Cause every girl want Oh s..."

In [19]:
new_merged_data_df.rename(columns = {'artists':'Artists', 'danceability':'Danceability', 'energy':'Energy', 'popularity':'Popularity', 'year':'Year'}, inplace=True)
new_merged_data_df.head()

,Name,Date,New_Genre,Artists,Danceability,Energy,Popularity,Year,cleaned_lyrics
0,I Like It,"April 6, 2018",Trap,"['Cardi B', 'Bad Bunny', 'J Balvin']",0.816,0.726,81.0,2018.0,"Like It Yeah Girl, wish could spend time every..."
1,I Like It,"April 6, 2018",Trap,"['Enrique Iglesias', 'Pitbull']",0.646,0.940,63.0,2010.0,"Like It Yeah Girl, wish could spend time every..."
2,I Like It,"April 6, 2018",Trap,"['Sammie', 'JT Money']",0.826,0.656,58.0,2000.0,"Like It Yeah Girl, wish could spend time every..."
3,Leave Me Alone,"March 14, 2018",Rap,['Flipp Dinero'],0.792,0.743,72.0,2019.0,"Leave Me Alone Yeah, yeah Yeah, miss got time ..."
4,Leave Me Alone,"March 14, 2018",Rap,['NF'],0.722,0.741,70.0,2019.0,"Leave Me Alone Yeah, yeah Yeah, miss got time ..."

In [27]:
# Create database connection
rds_connection_string =(f'postgres:{password}@localhost:5432/Song_db')
engine = create_engine(f'postgresql://{rds_connection_string}')

In [28]:
# Confirm tables
engine.table_names()

[]

In [30]:
new_merged_data_df.to_sql(name='premise', con=engine, if_exists='append', index=False)