In [1]:
import pandas as pd
from sqlalchemy import create_engine

In [8]:
spotify_file = "Data/Spotify_data 1999-2019.csv"
spotify_data_df = pd.read_csv(spotify_file)
spotify_data_df.head()

,acousticness,artists,danceability,duration_ms,energy,explicit,id,instrumentalness,key,liveness,loudness,mode,name,popularity,release_date,speechiness,tempo,valence,year
0,0.845,['Phillip Hermans'],0.716,156297,0.239,0,6xKsifCnYsVE8mHv17nzdq,0.000005,0,0.0789,-12.788,1,New Years in July,0,12/31/2019,0.0347,78.192,0.718,2019
1,0.437,['J-Dooly'],0.953,254067,0.606,1,3jVVpgqYbRqbWaluAOuU09,0.000000,6,0.1160,-5.635,0,Never.,8,12/31/2019,0.2910,121.015,0.376,2019
2,0.419,['Kuzo'],0.716,108500,0.528,1,2iGiOLN6XjdUdr8cflIrFq,0.000038,3,0.1050,-13.663,0,Priorites,2,12/31/2019,0.2910,80.121,0.526,2019
3,0.197,['Cain/Abel'],0.817,230333,0.415,0,0oTUViL923QVJUMbgbbH2D,0.000000,11,0.1360,-9.933,1,Said It (6 Years),0,12/31/2019,0.1140,83.993,0.417,2019
4,0.115,['Morgan Wallen'],0.545,185733,0.884,0,3746VOqCr3ys3lQdhmDoyH,0.000424,2,0.0496,-5.208,1,This Bar,72,12/31/2019,0.0817,110.015,0.272,2019

In [11]:
new_spotify_data_df = spotify_data_df[['artists', 'name', 'danceability', 'energy', 'popularity', 'year']].copy()
new_spotify_data_df.head()

,artists,name,danceability,energy,popularity,year
0,['Phillip Hermans'],New Years in July,0.716,0.239,0,2019
1,['J-Dooly'],Never.,0.953,0.606,8,2019
2,['Kuzo'],Priorites,0.716,0.528,2,2019
3,['Cain/Abel'],Said It (6 Years),0.817,0.415,0,2019
4,['Morgan Wallen'],This Bar,0.545,0.884,72,2019

In [13]:
new_spotify_data_df.to_csv('Data/adj_spotify_data.csv', index = False)